best_score: 0.8750957719311071
hyperparameters:
  colsample_bytree: 0.569746930326021
  learning_rate: 0.02692655251486473
  max_depth: 8
  n_estimators: 200
  num_leaves: 119
  reg_alpha: 4.258943089524393e-06
  reg_lambda: 1.9826980964985924e-05
  subsample: 0.8059264473611898
metadata:
  best_params:
    colsample_bytree: 0.569746930326021
    learning_rate: 0.02692655251486473
    max_depth: 8
    n_estimators: 200
    num_leaves: 119
    reg_alpha: 4.258943089524393e-06
    reg_lambda: 1.9826980964985924e-05
    subsample: 0.8059264473611898
  best_value: 0.8750957719311071
  completed_trials: 5
  mean_value: 0.8636657937388048
  model_type: lightgbm
  param_importances:
    colsample_bytree: !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      padsKqZSuz8=
    learning_rate: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      XIfGwTKZ1T8=
    max_depth: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      IgiX0kPcsT8=
    n_estimators: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      7N+RihsLwj8=
    num_leaves: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      f37GU+CCwj8=
    reg_alpha: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      DpAUR2S1sz8=
    reg_lambda: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      bTMohzhPqD8=
    subsample: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      KMyItFJzsz8=
  pruned_trials: 0
  std_value: 0.009296080662670504
  total_trials: 5
metric_name: roc_auc
model_name: lightgbm
