best_score: 0.8840095359920866
hyperparameters:
  colsample_bytree: 0.8925879806965068
  gamma: 5.457028747569545e-07
  learning_rate: 0.03476649150592621
  max_depth: 5
  min_child_weight: 6
  n_estimators: 100
  subsample: 0.728034992108518
metadata:
  best_params:
    colsample_bytree: 0.8925879806965068
    gamma: 5.457028747569545e-07
    learning_rate: 0.03476649150592621
    max_depth: 5
    min_child_weight: 6
    n_estimators: 100
    subsample: 0.728034992108518
  best_value: 0.8840095359920866
  completed_trials: 5
  mean_value: 0.8710598670683616
  model_type: xgboost
  param_importances:
    colsample_bytree: !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      CF7JwoxHsT8=
    gamma: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      fTlB28+M0D8=
    learning_rate: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      NjUCKNVmkT8=
    max_depth: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      87JCK68kuT8=
    min_child_weight: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      v5V8Kyg9sD8=
    n_estimators: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      zuLcDF4Eyj8=
    subsample: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      GQhuxTqw0j8=
  pruned_trials: 0
  std_value: 0.010546402989182942
  total_trials: 5
metric_name: roc_auc
model_name: xgboost
